---
title: "p8105_hw6_cev2129"
output: html_document
date: "2024-11-25"
---


```{r}
library(tidyverse)
library(modelr)
library(mgcv)
```
##Problem 2
```{r}
homicide_data = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")

homicide_data = homicide_data |>
  mutate(
    city_state = paste(city, state, sep = ", "),
    solved = ifelse(disposition == "Closed by arrest" | disposition == "Closed without arrest", 1, 0),
    victim_age = as.numeric(victim_age)
  ) |>
  filter(
    is.na(match(city_state, c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL"))) &
      (victim_race == "Black" | victim_race == "White")
  )
```

```{r}
baltimore<- homicide_data |>
  filter(city_state == "Baltimore, MD") 

logit_model <- glm(
  solved ~ victim_age + victim_sex + victim_race, 
  data = baltimore, 
  family = binomial()
)

 logit_model|>
  broom::tidy(conf.int = TRUE, conf.level = 0.95) |>  
  mutate(OR = exp(estimate),                         
         conf.low = exp(conf.low),                    
         conf.high = exp(conf.high)) |>              
  filter(term == "victim_sexMale") |>                      
  select(term, log_OR = estimate, OR, conf.low, conf.high, p.value) |>
  knitr::kable(digits = 3)    
```

```{r}
city_odds <- homicide_data |>
  group_by(city_state) |>
  nest() |> 
  mutate(
    model = purrr::map(data, ~ glm(solved ~ victim_age + victim_sex + victim_race, data = ., family = binomial())),
    tidy_model = purrr::map(model, ~ broom::tidy(., conf.int = TRUE))
  ) |> 
  unnest(tidy_model) |> 
  filter(term == "victim_sexMale") |> 
  mutate(
    OR = exp(estimate), 
    conf.low = exp(conf.low), 
    conf.high = exp(conf.high)
  ) |>
  select(city_state, OR, conf.low, conf.high, p.value)
```
```{r}
city_arranged <- city_odds |>
  arrange(OR) |> 
  mutate(city_state = factor(city_state, levels = city_state))

ggplot(city_arranged, aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +
  labs(
    title = "Estimated Odds Ratios for Solving Homicides by City",
    x = "City",
    y = "Odds Ratio (95% CI)"
  ) +
  theme_minimal()+
  theme(axis.text.y = element_text(size = 5))
```
This plot reflects the odds of solving homicides for male victims compared to female victims. Only four cities reflect an odds ratio greater than one, with the. majority of the odds ratios lying below one. 


##Problem 3
```{r}
bwt_data = read_csv("https://p8105.com/data/birthweight.csv")

bwt_data = bwt_data |>
  mutate(
    babysex = factor(babysex, levels = c(1, 2), labels = c("Male", "Female")),
    frace = factor(frace, levels = c(1, 2, 3, 4, 8, 9), 
                   labels = c("White", "Black", "Asian", "Puerto Rican", "Other", "Unknown")),
    malform = factor(malform, levels = c(0, 1), labels = c("Absent", "Present")),
    mrace = factor(mrace, levels = c(1, 2, 3, 4, 8), 
                   labels = c("White", "Black", "Asian", "Puerto Rican", "Other"))
  )

sum(is.na(bwt_data))
```


```{r}
bwt_model =  bwt_data |>
  lm(bwt ~ babysex + gaweeks + momage + ppbmi + smoken + malform, data = _) 

bwt_plot <- bwt_data |>
  modelr::add_predictions(bwt_model) |>
  modelr::add_residuals(bwt_model)
```
